In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np

In [7]:
a = [1, 2, 3]
a, type(a)

([1, 2, 3], list)

In [8]:
b = np.array([1, 2, 3])
b, type(b)

(array([1, 2, 3]), numpy.ndarray)

In [5]:
a.append(4)
a

[1, 2, 3, 4]

In [11]:
print(np.ones((1,5)))
print(np.ones((3,2)))

[[1. 1. 1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [12]:
print(np.zeros((2,2)))

[[0. 0.]
 [0. 0.]]


In [21]:
print(np.arange(10))
print(np.arange(3,7, dtype=np.float))
print(np.arange(3,10, 2))
print(list(range(3, 10)))

[0 1 2 3 4 5 6 7 8 9]
[3. 4. 5. 6.]
[3 5 7 9]
[3, 4, 5, 6, 7, 8, 9]


In [26]:
# 행렬 선언
np.array([[1,2,3], [1,2,3]])

array([[1, 2, 3],
       [1, 2, 3]])

In [42]:
# random으로 matrix 만들기
mat1 = np.random.randint(low=1, high=10, size=(3,2))
mat2 = np.random.rand(2,5)
print(mat1)
print(mat2)
np.random.randint(2,4)

[[7 6]
 [7 8]
 [1 3]]
[[0.67367919 0.16884169 0.63482177 0.45787106 0.15350952]
 [0.86789236 0.6875947  0.86368827 0.02284515 0.29187889]]


2